# Disable some built-in rules
config:
  line-length: false
  no-inline-html: false

# Define glob expressions to use (only valid at root)
globs:
  - "**/*.md"

# Define glob expressions to ignore
ignores:
  - "ignore*.md"